### ISSUE TITLE
Move to React

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#3]

**Comment by dvirberlo** [comment]
#11 open

**Comment by dvirberlo** [comment]
It may be sensible to open a seperate issue for each of the following points, but for now, I will just spit it out here (laying out what we've talk privately):
1. It may be sensible to open a seperate issue for each of the following points, but for now, I will just spit it out here (laying out what we've talk privately):
2. I did not copied exactly the design of the original vanilla JS branch, and I thing all the margin and paddings should be reconsidered to make a more thoughtfull design.
3. I did not use the SweetAlert for popups, except for the about popup, that I accidently put everything as the title.
4. I did not implement "Solved Mazes" section, since in short screens it made the board very small. another design issue to discuss.
5. I forgot to reset the board after a user mistake. Easy fix.
6. I removed the "fork me on github" banner since, in narrow screens it covered the board:
![image](https://user-images.githubusercontent.com/43615701/233559932-d6137229-732a-4bf0-b24f-4a2c542988ee.png)

**Comment by dvirberlo** [comment]
7. in the new react version, I tried, as much as possible, to reuse the original code.
But, the View and ViewModel did not make sense to me when I built it, so I dumped them and use React's state management patterns instead (state, context etc.)
8. Overall, the files structure is OK, but I think it can be more understandable.

**Comment by dvirberlo** [comment]
9. The "Cheat" button is always hidden and is not implemented

**Comment by dvirberlo** [comment]
10. Forgot to use the original font

**Comment by eternaleclipse** [comment]
I split everything to separate issues, let's do this 🙌 
I'm leaving this open until we actually merge to `main`.

**Comment by dvirberlo** [comment]
Looks like separate issues have been opened.
Closing this.
